version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "05:00"
    timezone: Asia/Istanbul
  open-pull-requests-limit: 0
  reviewers:
  - starikcetin
  labels:
  - dependencies
