version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Istanbul
  open-pull-requests-limit: 10
  reviewers:
  - starikcetin
  labels:
  - dependencies
